### ISSUE TITLE
Turning on safe search

### ISSUE THREAD

**Issue by ThoseGuysInTown** [vadimdemedes/google-images#23]
I'm trying to turn on safe search but it doesn't seem to be working. Not sure if its the format or something with the lib, either way, help would be much appreciated.

Code:
```
client.search(queryText,{
    	safe: 'high',
    	page: 1
    })
    .then(function (images) {

        console.log(images);
        res.json(
            images
        );

    })
```

**Comment by sholladay** [comment]
I implemented this, so hopefully I can help.

We have a test that verifies `safe` gets properly serialized and [sent in a real network request](https://github.com/vadimdemedes/google-images/blob/75862c51a99713bef5ddbda1fcfb9ae2fe445664/test.js#L179). Try to run this locally on your machine and see if it passes.

Also be sure to check out Google's [parameters documentation](https://developers.google.com/custom-search/json-api/v1/reference/cse/list#parameters), which includes `safe`.

Your code looks correct to me and I don't see anything amiss right away in either the library or Google's documentation.

As of now, my best guess is that there is a simple typo somewhere in your actual code. It is also likely that SafeSearch just isn't doing a good job with your query. Note that if you _explicitly_ search for something, SafeSearch isn't going to scrub all of the results. It's an imperfect filter that is really meant to tame borderline innocuous searches that have double meanings.

A more remote possibility is that Google changed something recently without incrementing the API version, though I doubt it. In the off chance this is the case, I would try:

1. Try capitalizing the value, upper casing it, etc.
2. Try `on` instead of `high`.
3. Try making it boolean `true`.

**Comment by ThoseGuysInTown** [comment]
Thanks so much! You were right, SafeSearch just wasn't blocking stuff because of the search I was doing. It seems to be removing the double meanings like you're saying. 

Again, Thank you.

**Comment by vadimdemedes** [comment]
Thanks @sholladay for helping resolve this!
